import type { PromptEngineResult } from '@/types/prompt.types';

export type CursorExportType = 'rule' | 'agent' | 'skill' | 'command';

interface CursorExportOptions {
  name: string;
  description?: string;
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 50);
}

export function exportAsCursorRule(result: PromptEngineResult, options: CursorExportOptions): string {
  const slug = slugify(options.name);
  return `---
description: ${options.description || options.name}
globs:
alwaysApply: false
---

# ${options.name}

${result.structuredPrompt}

${result.metaPrompt ? `## System Instructions\n\n${result.metaPrompt}` : ''}
`.trim() + '\n';
}

export function exportAsCursorAgent(result: PromptEngineResult, options: CursorExportOptions): string {
  const lines = [
    `# ${options.name}`,
    '',
    options.description ? `${options.description}` : '',
    '',
    '## Role',
    '',
    result.metaPrompt || result.structuredPrompt,
    '',
    '## Instructions',
    '',
    result.structuredPrompt,
    '',
    '## Tools',
    '',
    '- Read files',
    '- Write files',
    '- Run terminal commands',
    '- Search codebase',
    '',
  ];
  return lines.filter((l, i) => !(l === '' && lines[i - 1] === '')).join('\n').trim() + '\n';
}

export function exportAsCursorSkill(result: PromptEngineResult, options: CursorExportOptions): string {
  return `# SKILL.md — ${options.name}

## Description
${options.description || 'A skill generated from Garry Clear Prompt.'}

## When to Use
Use this skill when you need to: ${options.name.toLowerCase()}.

## Steps

### Step 1: Understand the Context
Read the relevant files and understand the current state.

### Step 2: Execute
${result.structuredPrompt}

${result.metaPrompt ? `### System Context\n${result.metaPrompt}` : ''}

### Step 3: Validate
Verify the output meets the requirements.

## Notes
- Generated by Garry Clear Prompt
- Prompt quality score: ${result.rating.totalScore}/100 (${result.rating.band})
- Estimated tokens: ${result.tokenEstimate.totalTokens.low}–${result.tokenEstimate.totalTokens.high}
`;
}

export function exportAsCursorCommand(result: PromptEngineResult, options: CursorExportOptions): string {
  const slug = slugify(options.name);
  return `---
name: ${slug}
description: ${options.description || options.name}
---

${result.structuredPrompt}
`;
}

export function exportForCursor(
  type: CursorExportType,
  result: PromptEngineResult,
  options: CursorExportOptions
): { content: string; filename: string; mimeType: string } {
  const slug = slugify(options.name);

  switch (type) {
    case 'rule':
      return {
        content: exportAsCursorRule(result, options),
        filename: `${slug}.mdc`,
        mimeType: 'text/markdown',
      };
    case 'agent':
      return {
        content: exportAsCursorAgent(result, options),
        filename: `${slug}.md`,
        mimeType: 'text/markdown',
      };
    case 'skill':
      return {
        content: exportAsCursorSkill(result, options),
        filename: 'SKILL.md',
        mimeType: 'text/markdown',
      };
    case 'command':
      return {
        content: exportAsCursorCommand(result, options),
        filename: `${slug}.md`,
        mimeType: 'text/markdown',
      };
  }
}
