import type { PromptEngineResult } from '@/types/prompt.types';

export function exportAsMarkdown(result: PromptEngineResult): string {
  const lines: string[] = [];

  lines.push('# Garry Clear Prompt -- Export');
  lines.push('');
  lines.push(`**Score:** ${result.rating.totalScore}/100 (${result.rating.band})`);
  lines.push('');

  // Structured prompt
  lines.push('## Prompt');
  lines.push('');
  lines.push('```');
  lines.push(result.structuredPrompt);
  lines.push('```');
  lines.push('');

  // Meta prompt
  if (result.metaPrompt) {
    lines.push('## Meta Prompt');
    lines.push('');
    lines.push('```');
    lines.push(result.metaPrompt);
    lines.push('```');
    lines.push('');
  }

  // Rating breakdown
  lines.push('## Rating Breakdown');
  lines.push('');
  lines.push('| Dimension | Score |');
  lines.push('|-----------|-------|');
  const dims = result.rating.dimensions;
  lines.push(`| Clarity | ${dims.clarity.score}/${dims.clarity.maxScore} |`);
  lines.push(`| Constraints | ${dims.constraints.score}/${dims.constraints.maxScore} |`);
  lines.push(`| Structure | ${dims.structure.score}/${dims.structure.maxScore} |`);
  lines.push(`| Token Efficiency | ${dims.tokenEfficiency.score}/${dims.tokenEfficiency.maxScore} |`);
  lines.push(`| Risk Penalty | ${dims.riskPenalty.score} |`);
  lines.push('');

  // Suggestions
  if (result.rating.suggestions.length > 0) {
    lines.push('## Suggestions');
    lines.push('');
    for (const suggestion of result.rating.suggestions) {
      lines.push(`- ${suggestion}`);
    }
    lines.push('');
  }

  // Token estimate
  lines.push('## Token Estimate');
  lines.push('');
  lines.push(`- Input: ${result.tokenEstimate.inputTokens.low}--${result.tokenEstimate.inputTokens.high} tokens`);
  lines.push(`- Output: ${result.tokenEstimate.outputTokens.low}--${result.tokenEstimate.outputTokens.high} tokens`);
  lines.push(`- Total: ${result.tokenEstimate.totalTokens.low}--${result.tokenEstimate.totalTokens.high} tokens`);
  lines.push('');

  // Model recommendation
  lines.push('## Model Recommendation');
  lines.push('');
  lines.push(`- **Recommended:** ${result.modelRecommendation.recommended} (confidence: ${result.modelRecommendation.confidence})`);
  lines.push(`- **Alternative:** ${result.modelRecommendation.alternative}`);
  if (result.modelRecommendation.avoid) {
    lines.push(`- **Avoid:** ${result.modelRecommendation.avoid}`);
  }
  lines.push(`- **Reason:** ${result.modelRecommendation.reason}`);
  lines.push('');

  // Lint warnings
  if (result.lintWarnings.length > 0) {
    lines.push('## Lint Warnings');
    lines.push('');
    for (const warning of result.lintWarnings) {
      lines.push(`- **[${warning.severity.toUpperCase()}]** ${warning.rule}: ${warning.message}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by Garry Clear Prompt*');

  return lines.join('\n');
}
