import type { PromptEngineResult } from '@/types/prompt.types';
import { APP_NAME } from '@/common/constants';

export function exportAsText(result: PromptEngineResult): string {
  const lines: string[] = [];

  lines.push(`${APP_NAME.toUpperCase()} -- EXPORT`);
  lines.push('='.repeat(40));
  lines.push('');
  lines.push(`Score: ${result.rating.totalScore}/100 (${result.rating.band})`);
  lines.push('');

  lines.push('PROMPT:');
  lines.push('-'.repeat(20));
  lines.push(result.structuredPrompt);
  lines.push('');

  if (result.metaPrompt) {
    lines.push('META PROMPT:');
    lines.push('-'.repeat(20));
    lines.push(result.metaPrompt);
    lines.push('');
  }

  lines.push('SUGGESTIONS:');
  lines.push('-'.repeat(20));
  for (const s of result.rating.suggestions) {
    lines.push(`  * ${s}`);
  }
  lines.push('');

  lines.push('TOKEN ESTIMATE:');
  lines.push('-'.repeat(20));
  lines.push(
    `  Input:  ${result.tokenEstimate.inputTokens.low}-${result.tokenEstimate.inputTokens.high}`
  );
  lines.push(
    `  Output: ${result.tokenEstimate.outputTokens.low}-${result.tokenEstimate.outputTokens.high}`
  );
  lines.push(
    `  Total:  ${result.tokenEstimate.totalTokens.low}-${result.tokenEstimate.totalTokens.high}`
  );
  lines.push('');

  lines.push('MODEL: ' + result.modelRecommendation.recommended);
  lines.push('REASON: ' + result.modelRecommendation.reason);
  lines.push('');
  lines.push(`-- Generated by ${APP_NAME} --`);

  return lines.join('\n');
}
