import JSZip from 'jszip';
import type { PromptEngineResult } from '@/types/prompt.types';
import { APP_NAME } from '@/common/constants';
import { exportAsMarkdown } from './markdown-exporter';
import { exportAsJson } from './json-exporter';

export async function exportAsZip(result: PromptEngineResult): Promise<Blob> {
  const zip = new JSZip();

  // Core prompt files
  zip.file('prompt.txt', result.structuredPrompt);
  if (result.metaPrompt) {
    zip.file('meta-prompt.txt', result.metaPrompt);
  }

  // Full analysis in markdown
  zip.file('analysis.md', exportAsMarkdown(result));

  // Machine-readable JSON
  zip.file('config.json', exportAsJson(result));

  // Rating summary
  const ratingSummary = [
    `# Prompt Quality Report`,
    ``,
    `**Score:** ${result.rating.totalScore}/100 (${result.rating.band})`,
    ``,
    `## Dimensions`,
    ...Object.values(result.rating.dimensions).map(d =>
      `- **${d.name}:** ${d.score}/${d.maxScore} — ${d.feedback}`
    ),
    ``,
    `## Suggestions`,
    ...result.rating.suggestions.map(s => `- ${s}`),
    ``,
    `## Token Estimate`,
    `- Input: ${result.tokenEstimate.inputTokens.low}–${result.tokenEstimate.inputTokens.high}`,
    `- Output: ${result.tokenEstimate.outputTokens.low}–${result.tokenEstimate.outputTokens.high}`,
    `- Total: ${result.tokenEstimate.totalTokens.low}–${result.tokenEstimate.totalTokens.high}`,
    ``,
    `## Model Recommendation`,
    `- Recommended: ${result.modelRecommendation.recommended}`,
    `- Alternative: ${result.modelRecommendation.alternative}`,
    `- Reason: ${result.modelRecommendation.reason}`,
  ].join('\n');

  zip.file('report.md', ratingSummary);

  // Lint warnings
  if (result.lintWarnings.length > 0) {
    const lintContent = result.lintWarnings.map(w =>
      `[${w.severity.toUpperCase()}] ${w.rule}: ${w.message}\n  Suggestion: ${w.suggestion}`
    ).join('\n\n');
    zip.file('lint-warnings.txt', lintContent);
  }

  // MCP suggestions
  if (result.mcpSuggestions.length > 0) {
    const mcpContent = result.mcpSuggestions.map(s =>
      `${s.name} (${s.permission})\n  ${s.description}\n  Safe envs: ${s.safeEnvironments.join(', ')}\n  Risk: ${s.riskNote}`
    ).join('\n\n');
    zip.file('mcp-suggestions.txt', mcpContent);
  }

  // README
  zip.file('README.md', [
    `# ${APP_NAME} Export`,
    ``,
    `This package was generated by [${APP_NAME}](https://github.com/garry-clear-prompt).`,
    ``,
    `## Contents`,
    `- \`prompt.txt\` — The structured prompt`,
    result.metaPrompt ? `- \`meta-prompt.txt\` — System instructions / meta prompt` : null,
    `- \`analysis.md\` — Full analysis in Markdown`,
    `- \`config.json\` — Machine-readable configuration`,
    `- \`report.md\` — Quality score report`,
    result.lintWarnings.length > 0 ? `- \`lint-warnings.txt\` — Lint warnings` : null,
    result.mcpSuggestions.length > 0 ? `- \`mcp-suggestions.txt\` — MCP tool suggestions` : null,
    ``,
    `**Score:** ${result.rating.totalScore}/100 (${result.rating.band})`,
    `**Estimated tokens:** ${result.tokenEstimate.totalTokens.low}–${result.tokenEstimate.totalTokens.high}`,
  ].filter(Boolean).join('\n'));

  return zip.generateAsync({ type: 'blob' });
}
