import { exportAsMarkdown } from '@/lib/exporters/markdown-exporter';
import { createMockEngineResult } from '../../../mock';

describe('markdown-exporter', () => {
  describe('exportAsMarkdown', () => {
    const result = createMockEngineResult();

    it('should include the app name in the header', () => {
      const md = exportAsMarkdown(result);
      expect(md).toContain('Garry Clear Prompt');
    });

    it('should include the score and band', () => {
      const md = exportAsMarkdown(result);
      expect(md).toContain('72/100');
      expect(md).toContain('average');
    });

    it('should include the structured prompt in a code block', () => {
      const md = exportAsMarkdown(result);
      expect(md).toContain('```');
      expect(md).toContain('Create a REST API endpoint for user management.');
    });

    it('should include the meta prompt when present', () => {
      const md = exportAsMarkdown(result);
      expect(md).toContain('## Meta Prompt');
      expect(md).toContain('expert backend developer');
    });

    it('should omit meta prompt section when empty', () => {
      const noMeta = createMockEngineResult({ metaPrompt: '' });
      const md = exportAsMarkdown(noMeta);
      expect(md).not.toContain('## Meta Prompt');
    });

    it('should include rating breakdown table', () => {
      const md = exportAsMarkdown(result);
      expect(md).toContain('Rating Breakdown');
      expect(md).toContain('Clarity');
      expect(md).toContain('18/25');
    });

    it('should include suggestions', () => {
      const md = exportAsMarkdown(result);
      expect(md).toContain('## Suggestions');
      expect(md).toContain('Add output format');
    });

    it('should include token estimate', () => {
      const md = exportAsMarkdown(result);
      expect(md).toContain('Token Estimate');
      expect(md).toContain('20');
    });

    it('should include model recommendation', () => {
      const md = exportAsMarkdown(result);
      expect(md).toContain('Model Recommendation');
      expect(md).toContain('balanced');
    });

    it('should include lint warnings when present', () => {
      const md = exportAsMarkdown(result);
      expect(md).toContain('Lint Warnings');
      expect(md).toContain('no-output-format');
    });

    it('should omit lint warnings section when empty', () => {
      const noLint = createMockEngineResult({ lintWarnings: [] });
      const md = exportAsMarkdown(noLint);
      expect(md).not.toContain('## Lint Warnings');
    });

    it('should end with generated-by footer', () => {
      const md = exportAsMarkdown(result);
      expect(md).toContain('*Generated by Garry Clear Prompt*');
    });
  });
});
