import { exportAsText } from '@/lib/exporters/text-exporter';
import { createMockEngineResult } from '../../../mock';

describe('text-exporter', () => {
  describe('exportAsText', () => {
    const result = createMockEngineResult();

    it('should include the app name in uppercase header', () => {
      const text = exportAsText(result);
      expect(text).toContain('GARRY CLEAR PROMPT');
    });

    it('should include the score', () => {
      const text = exportAsText(result);
      expect(text).toContain('72/100');
    });

    it('should include the structured prompt', () => {
      const text = exportAsText(result);
      expect(text).toContain('PROMPT:');
      expect(text).toContain('REST API endpoint');
    });

    it('should include meta prompt when present', () => {
      const text = exportAsText(result);
      expect(text).toContain('META PROMPT:');
      expect(text).toContain('expert backend developer');
    });

    it('should omit meta prompt section when empty', () => {
      const noMeta = createMockEngineResult({ metaPrompt: '' });
      const text = exportAsText(noMeta);
      expect(text).not.toContain('META PROMPT:');
    });

    it('should include suggestions', () => {
      const text = exportAsText(result);
      expect(text).toContain('SUGGESTIONS:');
      expect(text).toContain('Add output format');
    });

    it('should include token estimate', () => {
      const text = exportAsText(result);
      expect(text).toContain('TOKEN ESTIMATE:');
    });

    it('should include model recommendation', () => {
      const text = exportAsText(result);
      expect(text).toContain('MODEL: balanced');
    });

    it('should end with generated-by footer', () => {
      const text = exportAsText(result);
      expect(text).toContain('Generated by Garry Clear Prompt');
    });
  });
});
